version: '3'
services:
  db:
    image: postgres:14
    container_name: wecom_db
    restart: always
    environment:
      POSTGRES_USER: nata
      POSTGRES_PASSWORD: nata1234
      POSTGRES_DB: wecom_archive
    volumes:
      - ./data/db:/var/lib/postgresql/data

  archive:
    image: python:3.11
    container_name: wecom_archive
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config:/app/config
      - ./data:/app/data
    command: bash -c "pip install -r requirements.txt && python fetcher.py"
    depends_on:
      - db

  web:
    image: python:3.11
    container_name: wecom_web
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config:/app/config
    ports:
      - "8080:8080"
    command: bash -c "pip install -r requirements.txt && python server.py"
    depends_on:
      - db
